$(shell mkdir -p rootfsimg/build)

APPS = hello_xsai after_workload gemm_precomp busybox before_workload llama.cpp pmu_test ame_hw_probe
# trap qemu_trap dtc lkvm-static

APPS_DIR = $(addprefix apps/, $(APPS))

# Guest init configuration.  Keep this list minimal: only stable,
# documented switches live here.  One-off experiment knobs (panel probe,
# whole-K sweeps, output-pipeline preflights, flash-attn variants,
# checkpoint-on-shape, sparse progress, async batching) were removed
# 2026-09-01; whole-K BF16 is the fixed AME path in xsai-workloads.sh.
XSAI_INIT_MODE ?= manual
ifeq ($(XSAI_INIT_MODE),ci)
XSAI_WORKLOAD ?= llama-fake-bench-suite
XSAI_AUTO_EXIT ?= 1
XSAI_DROP_SHELL ?= 0
else
ifeq ($(XSAI_INIT_MODE),shell)
XSAI_WORKLOAD ?= none
XSAI_AUTO_EXIT ?= 0
XSAI_DROP_SHELL ?= 1
else
XSAI_WORKLOAD ?= llama-fake-bench-suite
XSAI_AUTO_EXIT ?= 0
XSAI_DROP_SHELL ?= 1
endif
endif
XSAI_RUN_AFTER_WORKLOAD ?= 1
XSAI_DUMP_THP ?= 1
XSAI_TRACE_WORKLOAD ?= 1
XSAI_LLAMA_TEST_BACKEND_OPS ?= 1
XSAI_LLAMA_FAKE_BENCH_MODELS ?=
XSAI_LLAMA_FAKE_BENCH_P ?= 128
XSAI_LLAMA_FAKE_BENCH_N ?= 0
XSAI_LLAMA_FAKE_BENCH_R ?= 1
XSAI_LLAMA_FAKE_BENCH_WARMUP ?= 0
XSAI_LLAMA_FAKE_BENCH_ESTIMATE_LAYERS ?= 1
XSAI_LLAMA_FAKE_BENCH_FA ?= 0
XSAI_LLAMA_FAKE_BENCH_TYPE_K ?= f16
XSAI_LLAMA_FAKE_BENCH_TYPE_V ?= f16
XSAI_TEST_BACKEND_OPS_NEMU_SIGNAL ?= 1
XSAI_GGML_AME_LOG ?= 0

.PHONY: rootfsimg xsai-init-config $(APPS_DIR) clean

rootfsimg: xsai-init-config $(APPS_DIR)

xsai-init-config:
	@mkdir -p rootfsimg/build
	@{ \
	  echo "# Generated by firmware/riscv-rootfs/Makefile"; \
	  printf "XSAI_MODE='%s'\n" "$(XSAI_INIT_MODE)"; \
	  printf "WORKLOAD='%s'\n" "$(XSAI_WORKLOAD)"; \
	  printf "AUTO_EXIT='%s'\n" "$(XSAI_AUTO_EXIT)"; \
	  printf "DROP_SHELL='%s'\n" "$(XSAI_DROP_SHELL)"; \
	  printf "RUN_AFTER_WORKLOAD='%s'\n" "$(XSAI_RUN_AFTER_WORKLOAD)"; \
	  printf "DUMP_THP='%s'\n" "$(XSAI_DUMP_THP)"; \
	  printf "TRACE_WORKLOAD='%s'\n" "$(XSAI_TRACE_WORKLOAD)"; \
	  printf "XSAI_LLAMA_TEST_BACKEND_OPS='%s'\n" "$(XSAI_LLAMA_TEST_BACKEND_OPS)"; \
	  printf "XSAI_LLAMA_FAKE_BENCH_MODELS='%s'\n" "$(XSAI_LLAMA_FAKE_BENCH_MODELS)"; \
	  printf "XSAI_LLAMA_FAKE_BENCH_P='%s'\n" "$(XSAI_LLAMA_FAKE_BENCH_P)"; \
	  printf "XSAI_LLAMA_FAKE_BENCH_N='%s'\n" "$(XSAI_LLAMA_FAKE_BENCH_N)"; \
	  printf "XSAI_LLAMA_FAKE_BENCH_R='%s'\n" "$(XSAI_LLAMA_FAKE_BENCH_R)"; \
	  printf "XSAI_LLAMA_FAKE_BENCH_WARMUP='%s'\n" "$(XSAI_LLAMA_FAKE_BENCH_WARMUP)"; \
	  printf "XSAI_LLAMA_FAKE_BENCH_ESTIMATE_LAYERS='%s'\n" "$(XSAI_LLAMA_FAKE_BENCH_ESTIMATE_LAYERS)"; \
	  printf "XSAI_LLAMA_FAKE_BENCH_FA='%s'\n" "$(XSAI_LLAMA_FAKE_BENCH_FA)"; \
	  printf "XSAI_LLAMA_FAKE_BENCH_TYPE_K='%s'\n" "$(XSAI_LLAMA_FAKE_BENCH_TYPE_K)"; \
	  printf "XSAI_LLAMA_FAKE_BENCH_TYPE_V='%s'\n" "$(XSAI_LLAMA_FAKE_BENCH_TYPE_V)"; \
	  printf "XSAI_TEST_BACKEND_OPS_NEMU_SIGNAL='%s'\n" "$(XSAI_TEST_BACKEND_OPS_NEMU_SIGNAL)"; \
	  printf "GGML_AME_LOG='%s'\n" "$(XSAI_GGML_AME_LOG)"; \
	} > rootfsimg/build/xsai-init.conf

$(APPS_DIR): %:
	@echo "$$(date '+[rootfs %F %T %z] START $@')"
	@$(MAKE) -s -C $@ install
	@echo "$$(date '+[rootfs %F %T %z] END $@')"

clean:
	-$(foreach app, $(APPS_DIR), $(MAKE) -s -C $(app) clean ;)
	-rm -f rootfsimg/build/*

distclean:
	-$(foreach app, $(APPS_DIR), $(MAKE) -s -C $(app) distclean ;)
	-rm -f rootfsimg/build/*
	-rm -rf apps/busybox/repo
	-rm -rf apps/llama.cpp/repo
