/*
 * precomp_test.c — AME GEMM test using precomputed golden data
 *
 * No reference GEMM computation at runtime.
 * Golden A/B/C come from test_data.h (generated by gen_test_data.py).
 *
 * Each test:
 *   1. Copy A and B from .rodata into my_mem (required: AME needs
 *      physically contiguous memory in the reserved region)
 *   2. Call ggml_ame_gemm_tile_i8_i32_bT(A_mem, B_mem, C_ame)
 *   3. Compare C_ame against the precomputed golden C
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "ame.h"
#include "mem.h"
#include "test_data.h"

extern void ggml_ame_gemm_tile_i8_i32_bT(
    const int8_t  *A,
    const int8_t  *B,
    int32_t       *C
);

int precomp_test(void)
{
    const int M = PRECOMP_M;
    const int K = PRECOMP_K;
    const int N = PRECOMP_N;

    /* Allocate working buffers once, reuse across tests */
    int8_t  *A_mem   = (int8_t  *)my_malloc(M * K * sizeof(int8_t));
    int8_t  *B_mem   = (int8_t  *)my_malloc(N * K * sizeof(int8_t));
    int32_t *C_ame   = (int32_t *)my_malloc(M * N * sizeof(int32_t));

    if (!A_mem || !B_mem || !C_ame) {
        fprintf(stderr, "[precomp] memory allocation failed\n");
        return 1;
    }
    nemu_signal(DISABLE_TIME_INTR);
    nemu_signal(NOTIFY_PROFILER);
    printf("AME GEMM precomp test: %d cases, C(%dx%d) = A(%dx%d) * B^T(%dx%d)\n",
           PRECOMP_NUM_TESTS, M, N, M, K, N, K);
    ggml_ame_init();

    int total_fail = 0;

    for (int t = 0; t < PRECOMP_NUM_TESTS; t++) {
        /* Stage inputs into reserved memory */
        memcpy(A_mem, tc_A[t], M * K * sizeof(int8_t));
        memcpy(B_mem, tc_B[t], N * K * sizeof(int8_t));
        memset(C_ame, 0,       M * N * sizeof(int32_t));

        /* Run AME kernel */
        puts("+\n");
        ggml_ame_gemm_tile_i8_i32_bT(A_mem, B_mem, C_ame);
        puts("-\n");

        /* Compare against precomputed golden */
        int errors = 0;
        int first_idx = -1;
        for (int i = 0; i < M * N; i++) {
            if (C_ame[i] != tc_C[t][i]) {
                if (errors == 0){ first_idx = i; }
                errors++;
            }
        }

        if (errors) {
            printf("  [FAIL] %s: %d mismatches, first@%d ame=%d gold=%d\n",
                   tc_names[t], errors, first_idx,
                   C_ame[first_idx], tc_C[t][first_idx]);
            total_fail++;
        } else {
            printf("  [PASS] %s\n", tc_names[t]);
        }
    }

    my_free(A_mem);
    my_free(B_mem);
    my_free(C_ame);

    if (total_fail == 0) {
        printf("All %d precomp tests PASSED.\n", PRECOMP_NUM_TESTS);
        return 0;
    } else {
        printf("%d/%d precomp tests FAILED.\n", total_fail, PRECOMP_NUM_TESTS);
        return 2;
    }
}
